name: Deploy Seven Stars Toolbox
run-name: Deploy Seven Stars Toolbox ${{ github.action_ref }} by ${{ github.actor }}

on:
  push:
    tags:
      - "seven-stars-toolbox/v*"
  workflow_dispatch:


env:
  PROJECT_PATH: SevenStarsToolbox/SevenStarsToolbox.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: cleaning
        run: dotnet nuget locals all --clear

      - name: Restoring
        run: dotnet restore ${{ env.PROJECT_PATH }} -r win-x64

      - name: Building
        run: dotnet build ${{ env.PROJECT_PATH }} -c Release -r win-x64 --no-restore

      - name: Deploying
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build -p:IncludeNativeLibrariesForSelfExtract=true

#      - uses: actions/create-release@v1
#        id: create_release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: ${{ github.ref }}
#
#      - uses: csexton/release-asset-action@v3
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          pattern: SevenStarsToolbox/bin/Release/net8.0-windows/win-x64/publish/*.exe
#          release-url: ${{ steps.create_release.outputs.upload_url }}
      
      - name: Release (auto)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          files: ${{ github.workspace }}/SevenStarsToolbox/bin/Release/net8.0-windows/win-x64/publish/*.exe
      
      - name: Release (manually)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.action_ref }}
          tag_name: ${{ github.action_ref }}
          files: ${{ github.workspace }}/SevenStarsToolbox/bin/Release/net8.0-windows/win-x64/publish/*.exe
